
// Function to generate random characters
function generateChars() {
	var chars = "ABCDEFGHIJKLMNOPQRSTUVWXTZ";
	var string_length = 7;
	var generateChars = '';
	for (var i=0; i<string_length; i++) {
		var randomString = Math.floor(Math.random() * chars.length);
		generateChars += chars.substring(randomString,randomString+1);
	}
	document.randform.randomfield.value = generateChars;
	var res = [];
	res = generateChars.trim().split("");
	document.randform.charArr.value = res; 

/*	var randStr;
	randStr = getCombinations(res);
	document.randform.combP.value = randStr;
*/
}

// Generate all combinations in different length but some words are missing	
function getCombinations(chars) {
  var result = [];

  var f = function(prefix, chars) {
    for (var i = 0; i < chars.length; i++) {
      result.push(prefix + chars[i]);
      f(prefix + chars[i], chars.slice(i + 1));
    }
  }

  f('', chars);
  return result;
}

function bubbleSortString(strText) {
	var resort = false;
	// walk the character array, starting from second position, 
	// transposing characters of lesser value 

	if (typeof(strText) != "string") { 
		console.log("Nope!");
	}
	
	var charArray = strText.split('');
	
	for (x = 1; x < charArray.length; x++) {
		if (charArray[x] < charArray[x - 1]) {
			var temp = charArray[x - 1]; // store the moving value
			charArray[x - 1] = charArray[x]; // overwrite the stored value
			charArray[x] = temp;
			
			strText = charArray.join('');
			resort = true;
		}
	}
	
	// now call myself until there are no more resorts!
	if (resort) { 
		bubbleSortString(strText); 
	} else {
		console.log("Sorted Text: " + strText);
	}

	return strText;
	
}

/*
1
12
123
13
132
2
21
213
23
231
3
31
312
32
321
*/


// Check if the user input letter from random string
function checkLetter(inputtxt)  {
      
    var alphaExp = /^[a-zA-Z]+$/; // RegEx
	if(inputtxt.value.match(alphaExp) && inputtxt.value.length <8){
		alert('Valid Input!!!');
		return true;
	}else{
		alert('Input is invalid!!! Try Again Please');
		inputtxt.focus();
		return false;
	}
}  

// Check FileAPI
function checkFileAPI() {
        if (window.File && window.FileReader && window.FileList && window.Blob) {
            reader = new FileReader();
            return true; 
        } else {
            alert('The File APIs are not supported by your browser.');
            return false;
        }
}

// Read txtFile
function readText(filePath) {
	var output = ""; //placeholder for text output
	if(filePath.files && filePath.files[0]) {           
		reader.onload = function (e) {
			output = e.target.result;
			displayContents(output);
		};//end onload()
		reader.readAsText(filePath.files[0]);
	}//end if html filelist support
	else if(ActiveXObject && filePath) { 
		try {
			reader = new ActiveXObject("Scripting.FileSystemObject");
			var file = reader.OpenTextFile(filePath, 1); //ActiveX File Object
			output = file.ReadAll(); //text contents of file
			file.Close(); //close file "input stream"
			displayContents(output);
		} catch (e) {
			if (e.number == -2146827859) {
				alert('Unable to process.'); 
			}
		}       
	}
	else { //
		return false;
	}       
	return true;
}

// Display input file
function displayContents(txt) {
        var content = document.getElementById('main'); 
        content.innerHTML = txt; //display output in DOM
} 

/* 
                    ,.ood888888888888boo.,
               .od888P^""            ""^Y888bo.
           .od8P''   ..oood88888888booo.    ``Y8bo.
        .odP'"  .ood8888888888888888888888boo.  "`Ybo.
      .d8'   od8'd888888888f`8888't888888888b`8bo   `Yb.
     d8'  od8^   8888888888[  `'  ]8888888888   ^8bo  `8b
   .8P  d88'     8888888888P      Y8888888888     `88b  Y8.
  d8' .d8'       `Y88888888'      `88888888P'       `8b. `8b
 .8P .88P            """"            """"            Y88. Y8.
 88  888                                              888  88
 88  888                                              888  88
 88  888.        ..                        ..        .888  88
 `8b `88b,     d8888b.od8bo.      .od8bo.d8888b     ,d88' d8'
  Y8. `Y88.    8888888888888b    d8888888888888    .88P' .8P
   `8b  Y88b.  `88888888888888  88888888888888'  .d88P  d8'
     Y8.  ^Y88bod8888888888888..8888888888888bod88P^  .8P
      `Y8.   ^Y888888888888888LS888888888888888P^   .8P'
        `^Yb.,  `^^Y8888888888888888888888P^^'  ,.dP^'
           `^Y8b..   ``^^^Y88888888P^^^'    ..d8P^'
               `^Y888bo.,            ,.od888P^'
                    "`^^Y888888888888P^^'"        

*/

/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMM8++++++++++++++++++++++++++++++++++++++++IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMM++++++++++++++++++++I++++++++++++++:++++++++++++++++++++?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++++++++++MM++++++++++++MM+++++++++++++++++++++++++++DMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMM7+++++++++=MMM++++++++++++++++++MMM++++++++++~MM++++++++++++++++++~MM~++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++DMMMMMM++++++++++++++++++++MMMO+~7OZ?:+~MMM++++++++++++++++++++MMMMMMM+++++++++7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO+++++++~MMMMMMMMMM+++++++++++++++++++++MMMMMMMMMMMMMMMM:++++++++++++++++++++MMMMMMMMMM+++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM7+++++++MMMMMMMMMMMMM++++++++++++++++++++++MMMMMMMMMMMMMMMMD+++++++++++++++++++++MMMMMMMMMMMMM:+++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMM+++++++MMMMMMMMMMMMMMMM++++++++++++++++++++++:MMMMMMMMMMMMMMMMM++++++++++++++++++++++MMMMMMMMMMMMMMMM+++++++MMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMNMMMMM++++++MMMMMMMMMMMMMMMMMMM++++++++++++++++++++++MMMMMMMMMMMMMMMMMM++++++++++++++++++++++:MMMMMMMMMMMMMMMMMM+++++++MMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMNMMMM++++++MMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++++++MMMMMMMMMMMMMMMMMM+++++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMM++++++MMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMM++++++MMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++++++MMMMMMMMMMMMMMMMMM+++++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMM:+++++MMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMM+++++IMMMMMMMMMMMMMMMMMMMMMMMMM:+++++++++++++++++++++MMMMMMMMMMMMMMMMMMMM++++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMM7
MMMMMMMMMMMNMMMM++++:MMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++++MMMMMMMMMMMMMMMMMMMM7++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMM7
MMMMMMMMMMMMMM++++=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMM7++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD++++DMMMMMMMMMMMM7
MMMMMMMMMMMMM++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++=MMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMNMMMMMMM7
MMMMMMMMMMMM+++=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++++++++~MMMMMMMMMMMMMMMMMMMMMMMMMMMM?++++++++++ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8++++MMMMMMMMMM7
MMMMMMMMMMM+++IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMNMMMMM7
MMMMMMMMMM+++7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMMMM7
MMMMMMMMM+++=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++MMMMMMMM7
MMMMMMMMN+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:+++MMMMMMM7
MMMMMMMM+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++7MMMMMM7
MMMMMMMM+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:+++MMMMMM7
MMMMMMM$+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++MMMDMM7
MMMMMMM+++7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++MMMMMM7
MMMMMMM+++:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++MMMNMM7
MMMMMMM8+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~+++MMMMMM7
MMMMDMMM+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMM7
MMMMMMMM+++=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO+++MMMMMMM7
MMMMMMMMM+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$?OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMMM7
MMMMMMMMM++++MMMMMMMMMMMMMMMMMMMMMMMMM:++++++++++ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++++++++:MMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMMMM7
MMMMMMNMMM++++MMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++MMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMM7
MMMMMMMMMMM++++MMMMMMMMMMMMMMMMMMMMM8+++++++++++++++++=MMMMMMM++++++MMMMMMMMMMMMMMMMMMMMMMMM++++++8MMMMMM7+++++++++++++++++~MMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMM7
MMMMMMMMMMMM++++MMMMMMMMMMMMMMMMMMMM++++++++++++++++++++:MMMN+++++++++MMMMMMMMMMMMMMMMMMMM:++++++++=MMMN++++++++++++++++++++MMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMM7
MMMMMMMMMMMMM++++:MMMMMMMMMMMMMMMMMM++++++++++++++++++++++:I+++++++++++MMMMMMMMMMMMMMMMMM++++++++++++M++++++++++++++++++++++MMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMM7
MMMMMMMMMMNMMM8++++MMMMMMMMMMMMMMMMM?+++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMM++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMM7
MMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMM++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMM++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMM~++++MMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMM++++:MMMMMMMMMMMMMM~++++++++++++++++++++++++++++++++++++MMMMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMM7+++++MMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMM++++++MMMMNMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMMMM=++++++++++++++++++++++++++++++++++++MMMMMMMMMMMM++++++MMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMM$+++++MMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMM:++++++++++++++++++++++++++++++++++++MMMMMMMMMM++++++MMMMMNMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMM++++++OMMMMMMM++++++++++++++++++++++++++++++++++++=MMMMN++++++++++++++++++++++++++++++++++++MMMMMMMM++++++$MMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMNMMMMMM++++++=MMMMM=+++++++++++++++++++++++++++++++++++8MMM++++++++++++++++++++++++++++++++++++MMMMM:+++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMM?+++++++DMM+++++++++++++++++++++++++++++++++++MM+++++++++++++++++++++++++++++++++++OMM++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMM++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMZ+++++++++++++++++++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ+++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7
777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777=
*/
					