var unscrambled = "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMM8++++++++++++++++++++++++++++++++++++++++IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMM++++++++++++++++++++I++++++++++++++:++++++++++++++++++++?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++++++++++MM++++++++++++MM+++++++++++++++++++++++++++DMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMM7+++++++++=MMM++++++++++++++++++MMM++++++++++~MM++++++++++++++++++~MM~++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++DMMMMMM++++++++++++++++++++MMMO+~7OZ?:+~MMM++++++++++++++++++++MMMMMMM+++++++++7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO+++++++~MMMMMMMMMM+++++++++++++++++++++MMMMMMMMMMMMMMMM:++++++++++++++++++++MMMMMMMMMM+++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7+++++++MMMMMMMMMMMMM++++++++++++++++++++++MMMMMMMMMMMMMMMMD+++++++++++++++++++++MMMMMMMMMMMMM:+++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++MMMMMMMMMMMMMMMM++++++++++++++++++++++:MMMMMMMMMMMMMMMMM++++++++++++++++++++++MMMMMMMMMMMMMMMM+++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMM++++++MMMMMMMMMMMMMMMMMMM++++++++++++++++++++++MMMMMMMMMMMMMMMMMM++++++++++++++++++++++:MMMMMMMMMMMMMMMMMM+++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMM++++++MMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++++++MMMMMMMMMMMMMMMMMM+++++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMM++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++++MMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++++++MMMMMMMMMMMMMMMMMM+++++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMM:+++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++IMMMMMMMMMMMMMMMMMMMMMMMMM:+++++++++++++++++++++MMMMMMMMMMMMMMMMMMMM++++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMM++++:MMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++++MMMMMMMMMMMMMMMMMMMM7++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMM7++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD++++DMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++=MMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMNMMMMMMMMMMMMMMMMMMMM+++=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++++++++~MMMMMMMMMMMMMMMMMMMMMMMMMMMM?++++++++++ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8++++MMMMMMMMMMMMMMMMMMMMMM+++IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMNMMMMMMMMMMMMMMMM+++7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMMMMM+++=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++MMMMMMMMMMMMMMMMMN+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:+++MMMMMMMMMMMMMMMM+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++7MMMMMMMMMMMMMMM+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:+++MMMMMMMMMMMMMM$+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++MMMDMMMMMMMMMM+++7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++MMMMMMMMMMMMMM+++:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++MMMNMMMMMMMMMM8+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~+++MMMMMMMMMMMDMMM+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMM+++=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO+++MMMMMMMMMMMMMMMMM+++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$?OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMMMMMMMMMMMM:++++++++++ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++++++++:MMMMMMMMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMMNMMM++++MMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++++++++++MMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMMMMMMMM8+++++++++++++++++=MMMMMMM++++++MMMMMMMMMMMMMMMMMMMMMMMM++++++8MMMMMM7+++++++++++++++++~MMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMMMMMMM++++++++++++++++++++:MMMN+++++++++MMMMMMMMMMMMMMMMMMMM:++++++++=MMMN++++++++++++++++++++MMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMMMMMMMMMM++++:MMMMMMMMMMMMMMMMMM++++++++++++++++++++++:I+++++++++++MMMMMMMMMMMMMMMMMM++++++++++++M++++++++++++++++++++++MMMMMMMMMMMMMMMMMMM++++MMMMMMMMMMMMMMMMMMMMMMMNMMM8++++MMMMMMMMMMMMMMMMM?+++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMM++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMMMMM++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMM++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMM~++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++:MMMMMMMMMMMMMM~++++++++++++++++++++++++++++++++++++MMMMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMM7+++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMM++++++MMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++MMMMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMMMM=++++++++++++++++++++++++++++++++++++MMMMMMMMMMMM++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$+++++MMMMMMMMMM+++++++++++++++++++++++++++++++++++++MMMMMM:++++++++++++++++++++++++++++++++++++MMMMMMMMMM++++++MMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++++OMMMMMMM++++++++++++++++++++++++++++++++++++=MMMMN++++++++++++++++++++++++++++++++++++MMMMMMMM++++++$MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMM++++++=MMMMM=+++++++++++++++++++++++++++++++++++8MMM++++++++++++++++++++++++++++++++++++MMMMM:+++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMM?+++++++DMM+++++++++++++++++++++++++++++++++++MM+++++++++++++++++++++++++++++++++++OMM++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMM++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++MMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMZ+++++++++++++++++++++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ+++++++++++++++++++++++++++++++++++MMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";
//var unscrambled = "ABCDEFG";

var fullSort = false;

function scrambleTheArt(asciiArt) {
	var imagePoints = [];
	
	// load the unscrambled image into an object array
	for (x = 0; x < asciiArt.length; x++) {
		var point = new Object();
		point.position = x;
		point.value = asciiArt[x];
		imagePoints.push(point);
	}

	// scramble up the positions
	var scrambledImagePoints = new Array(imagePoints.length);
	var writePos = 0;
	
	do {
		var moved = false;
		do {
			var rnd = getRandomInteger(imagePoints.length);
			if (imagePoints[rnd]) { 
				
				// copy the point
				scrambledImagePoints[writePos] = imagePoints[rnd];
				
				// clear the old point
				imagePoints[rnd] = '';
				
				// update position & move flag
				writePos++;
				moved = true;
			}
		} while (!moved);
	} while (getFirstFilled(imagePoints) > -1);
	
	return scrambledImagePoints;
}

function walkPoints(arrPoints) {
	for (var x = 0; x < arrPoints.length; x++) {
		console.log(arrPoints[x].position + ":" + arrPoints[x].value);
	}
		
}

// return index of first non-empty element in an array
// return -1 if none are found
function getFirstFilled(arr) {
	for (x = 0; x < arr.length; x++) {
		if (arr[x]) {
			return x;
		}
	}
	return -1;
}

function makeJson() {
	var stringified = JSON.stringify(scrambleTheArt(unscrambled));
	return stringified;
}

function parseJson(jsonString) {
	var jsonArt = JSON.parse(stringified);
	return jsonArt;
}

function bubbleSortPoints(arrPoints) {
	var resort = false;

	for (x = 1; x < arrPoints.length; x++) {
		if (arrPoints[x].position < arrPoints[x - 1].position) {
			var temp = arrPoints[x - 1]; // store the moving value
			arrPoints[x - 1] = arrPoints[x]; // overwrite the stored value
			arrPoints[x] = temp;
			
			resort = true;
		}
	}
	
/*	// now call myself until there are no more resorts!
	if (resort) { 
		bubbleSortPoints(arrPoints); 
	}
*/
	fullSort = resort;
	
	return arrPoints;
	
}

function bubbleSortString(strText) {
	var resort = false;
	// walk the character array, starting from second position, 
	// transposing characters of lesser value 

	if (typeof(strText) != "string") { 
		console.log("Nope!");
	}
	
	var charArray = strText.split('');
	
	for (x = 1; x < charArray.length; x++) {
		if (charArray[x] < charArray[x - 1]) {
			var temp = charArray[x - 1]; // store the moving value
			charArray[x - 1] = charArray[x]; // overwrite the stored value
			charArray[x] = temp;
			
			strText = charArray.join('');
			resort = true;
		}
	}
	
	// now call myself until there are no more resorts!
	if (resort) { 
		bubbleSortString(strText); 
	} else {
		console.log("Sorted Text: " + strText);
	}

	return strText;
	
}


function getRandomInteger(max) {
	var number = Math.floor((Math.random() * max));
	return number;
}


function drawArtPointGrid(asciiArt, lineBreak) {
	var out = "";
	
	for (x = 0; x < asciiArt.length; x++) {
		if (x % lineBreak == 0) {
			out += "<br />\n\r";
		} else {
			out += "<span class='artPoint' id='p" + x + "'></span>";
		}
	}

	$("#asciiArt").empty();
	$("#asciiArt").append(out);
	
}

function fillArtPointGrid(asciiArt, lineBreak) {
	for (x = 0; x < asciiArt.length; x++) {
		
		if (x % lineBreak != 0 ) {
			$("#p" + x).text(asciiArt[x]);
		}
	}
}

function fillArtPointGridFromArray(pointArray, lineBreak) {
	for (x = 0; x < pointArray.length; x++) {
		
		if (x % lineBreak != 0 ) {
			$("#p" + x).text(pointArray[x].value);
		}
	}
}

function getAsciiPointVals(pointArray) {
	var ret;
	for (x = 0; x < pointArray.length; x++) {
		ret += pointArray[x].value;
	}
	
	return ret;
}

function setAsciiPointVal(point, value) {
	$("#p" + point).text(value);
}

